### ISSUE TITLE
Fix data upload to marketplace (Trac #685)

### ISSUE THREAD

**Issue by smk78** [SasView/sasmodel-marketplace#2]
AJJ reports not working. May be a permissions problem following updates to server at UTK???

Migrated from http://trac.sasview.org/ticket/685
```json
{
    "status": "closed",
    "changetime": "2017-04-05T16:07:37",
    "_ts": "2017-04-05 16:07:37.919892+00:00",
    "description": "AJJ reports not working. May be a permissions problem following updates to server at UTK???",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Marketplace",
    "time": "2016-10-04T14:27:37",
    "component": "sasmodels Markeplace",
    "summary": "Fix data upload to marketplace",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by ajj** [comment]
Trac update at `2016/10/05 19:40:18`: 
* **ajj** changed owner from "" to "ajj"
* **ajj** changed status from "new" to "accepted"

**Comment by butlerpd** [comment]
Trac update at `2016/10/07 19:09:47`: **butler** changed priority from "blocker" to "critical"

**Comment by butlerpd** [comment]
Trac update at `2016/12/20 16:57:11`: **butler** changed component from "SasView" to "sasmodels Markeplace"

**Comment by butlerpd** [comment]
Trac update at `2017/03/08 14:48:15`: 
* **butler** changed _comment0 from "This is really an admin task and not a 4.1 release blocker - though it would be **REALLY** nice to be able to release 4.1 with announcement of a working marketplace.  Still, as we are closing down work on 4.1 release am moving this to 4.2 so as not to confuse things." to "1488984863068645"
* **butler** commented:

This is really an admin task and not a 4.1 release blocker - though it would be **REALLY** nice to be able to release 4.1 with announcement of a working marketplace.  Still, as we are closing down work on 4.1 release am moving this to 4.2 so as not to confuse things along with companion ticket #7.


* **butler** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"

**Comment by ajj** [comment]
Trac update at `2017/04/05 16:07:37`: 
* **ajj** commented:

Fixed now that new version of server is deployed


* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "accepted" to "closed"
