### ISSUE TITLE
marketplace not working under chrome

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodel-marketplace#21]
The Chrome browser does not allow access to models which have had example plots uploaded as part of the package (on windows or mac).  E.g.,

    http://marketplace.sasview.org/models/88/

Perhaps this is due to mixing https for cloudflare and mathjax with http for sasview and bootstrap?

Maybe get a free SSL certificate from Let's Encrypt (https://letsencrypt.org/) so we can use https for sasview?  Or some other certificate authority if someone has the budget for it.

**Comment by butlerpd** [comment]
Actually as of May 2021 (and probably for some time), neither Edge nor Chrome (on windows) will allow access to models that included the plot. Only Firefox on windows seems to work as expected.  This is becoming a big issue. Looking at @pkienzle comment if upgrading to using https will solve the problem this could go away after the "infrastructure" hackathon. If not we should dig deeper I guess.

**Comment by llimeht** [comment]
In my local testing, switching to Chart.js version 2.5 or newer seems to fix this.
