### ISSUE TITLE
Migrate marketplace to python3

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasmodel-marketplace#22]
Marketplace is currently implemented in python2.7.

**Comment by arm61** [comment]
I have unassigned myself, wasn't able to get what turned out to be a big job complete in the previous hackathon. For anyone brave enough to take it on https://github.com/arm61/sasmodel-marketplace

**Comment by arm61** [comment]
One of the reasons for difficulty was that using GitHub actions to automate the testing was not easy https://github.com/SasView/sasmodel-marketplace/pull/24
