### ISSUE TITLE
Update categories at marketplace (Trac #763)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasmodel-marketplace#3]
The categories at the marketplace need to be updated to one currently used in !SasView. 

Migrated from http://trac.sasview.org/ticket/763
```json
{
    "status": "closed",
    "changetime": "2017-09-06T10:29:47",
    "_ts": "2017-09-06 10:29:47.033975+00:00",
    "description": "The categories at the marketplace need to be updated to one currently used in !SasView. ",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Admin",
    "time": "2016-10-10T20:37:03",
    "component": "sasmodels Markeplace",
    "summary": "Update categories at marketplace",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "lewis",
    "type": "task"
}
```

**Comment by wpotrzebowski** [comment]
Trac update at `2016/10/11 14:59:37`: 
* **wojciech** changed owner from "wojciech" to "butler"
* **wojciech** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2016/10/11 15:01:55`: 
* **butler** changed milestone from "SasView 4.1.0" to "Admin Tasks"
* **butler** changed type from "defect" to "task"
