### ISSUE TITLE
Allow adding multiple c files into sasmodels-marketplace (Trac #765)

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasmodel-marketplace#4]
Currently only one python and one c model can be added. However model can reference multiple c files. This is especially the case when external functions are used. We want to allow uploading more than one c files. 

Migrated from http://trac.sasview.org/ticket/765
```json
{
    "status": "closed",
    "changetime": "2016-10-11T13:41:12",
    "_ts": "2016-10-11 13:41:12.603148+00:00",
    "description": "Currently only one python and one c model can be added. However model can reference multiple c files. This is especially the case when external functions are used. We want to allow uploading more than one c files. ",
    "reporter": "wojciech",
    "cc": "",
    "resolution": "wontfix",
    "workpackage": "SasModels Marketplace",
    "time": "2016-10-10T20:41:08",
    "component": "sasmodels Markeplace",
    "summary": "Allow adding multiple c files into sasmodels-marketplace",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2016/10/11 12:12:37`: **butler** commented:

Is this really the right answer?  A user can of course do this if they really choose but it seems like it might be more confusing than necessary to the external !SasView community?  The only reason I can see for more than one C file is to be able to call libraries -- however the user '''cannot''' upload libraries in the sense that the only purpose a separate library file is to have a repository of common routines that everyone can use.  Nothing uploaded in the marketplace at present can be moved to the \library.  If then this is just a routine taken from somewhere else I don't see why it cannot just be added to the C file and thus not breaking the paradigm of one model = one python and optionally 1 c file? 

Or do we want the marketplace to allow uploading of library routines as recommendations to be added?  

Also - it would probably be appropriate to list on the marketplace the list of currently available library routines.

**Comment by butlerpd** [comment]
Trac update at `2016/10/11 13:41:12`: 
* **butler** commented:

After some discussion have agreed to add library files for SASfit models to the sasmodels library.  These are written specifically to use GPU as well as CPU so encourage their use over other library routines.  However most important will need to document the library routines available.  Two new tickets are being generated for these.  In the meantime will close this ticket as "wont fix."  As we get feedback from users may revisit this later.


* **butler** changed resolution from "" to "wontfix"
* **butler** changed status from "new" to "closed"
