### ISSUE TITLE
Marketplace Admin Panel issues (Trac #925)

### ISSUE THREAD

**Issue by butlerpd** [SasView/sasmodel-marketplace#8]
There are several issues with the Admin part of the marketplace:

* The Admin pages have lost all the layout information.  Mostly just very ugly
* As part of that all the button graphics are broken
* The "change" button when it appears seems to be broken
* figuring out how to change the category of a model is non-trivial. It can be changed either by:
 * the person who uploaded it
 * if an admin other than that person only !SasView models can be changed and to do so requires going to Admim -> Sasview models -> model name (and of course the change button does not work)  Rather than Sasview models it should just say "edit model details" or some such

Migrated from http://trac.sasview.org/ticket/925
```json
{
    "status": "closed",
    "changetime": "2017-04-06T21:29:23",
    "_ts": "2017-04-06 21:29:23.264604+00:00",
    "description": "There are several issues with the Admin part of the marketplace:\n\n* The Admin pages have lost all the layout information.  Mostly just very ugly\n* As part of that all the button graphics are broken\n* The \"change\" button when it appears seems to be broken\n* figuring out how to change the category of a model is non-trivial. It can be changed either by:\n * the person who uploaded it\n * if an admin other than that person only !SasView models can be changed and to do so requires going to Admim -> Sasview models -> model name (and of course the change button does not work)  Rather than Sasview models it should just say \"edit model details\" or some such",
    "reporter": "butler",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-04-06T09:33:15",
    "component": "sasmodels Markeplace",
    "summary": "Marketplace Admin Panel issues",
    "priority": "major",
    "keywords": "",
    "milestone": "Admin Tasks",
    "owner": "ajj",
    "type": "defect"
}
```

**Comment by butlerpd** [comment]
Trac update at `2017/04/06 09:38:45`: **butler** changed description from:

> There are several issues with the Admin part of the marketplace:
> 
> * The Admin pages have lost all the layout information.  Mostly just very ugly
> * As part of that all the button graphics are broken
> * The "change" button when it appears seems to be broken
> * figuring out how to change the category of a model is non-trivial. It can be changed either by:
>  * the person who uploaded it
>  * if an admin other than that person only SasView models can be changed and to do so requires going to Admim -> Sasview models -> model name (and of course the change button does not work)

to:

> There are several issues with the Admin part of the marketplace:
> 
> * The Admin pages have lost all the layout information.  Mostly just very ugly
> * As part of that all the button graphics are broken
> * The "change" button when it appears seems to be broken
> * figuring out how to change the category of a model is non-trivial. It can be changed either by:
>  * the person who uploaded it
>  * if an admin other than that person only !SasView models can be changed and to do so requires going to Admim -> Sasview models -> model name (and of course the change button does not work)  Rather than Sasview models it should just say "edit model details" or some such

**Comment by ajj** [comment]
Trac update at `2017/04/06 13:16:07`: **ajj** commented:

- Layout is back (sort of and still a bit ugly)
- Graphics are back
- The Save button doesn't work as it is requiring that 'verified' and 'verified by' are set. This is a bug but requires more digging.

**Comment by ajj** [comment]
Trac update at `2017/04/06 20:17:20`: **ajj** commented:

- Layout is back properly for Admin pages.

**Comment by ajj** [comment]
Trac update at `2017/04/06 21:29:23`: 
* **ajj** changed resolution from "" to "fixed"
* **ajj** changed status from "new" to "closed"
